### ISSUE TITLE
IDA Pro Alternatives

### ISSUE THREAD

**Issue by ggarcia453** [agwaBom/AsmDepictor#4]
Hello team. 

I wanted to inquire about potential alternatives to IDA Pro for disassembling the binary files. I am currently using the Free version of IDA, which does not support headless or batch mode. Additionally I can't use the Pro version since I do not have a license for it. I know there is Ghidra, which has headless and batch mode, but is Ghidra compatible with the preprocessing script?

I appreciate any help with this. Thank you!

**Comment by agwaBom** [comment]
Hello ggarcia453,

Thank you for expressing interest in our work! 
I must preface my response with the disclaimer that I am not an expert on IDA and Ghidra. 
My expertise lies in language modeling, and I am no longer part of the team. 
Nonetheless, I will try to provide the best answer possible.

To begin with, I assume that Ghidra should be compatible with IDA scripts when you do the conversion to the Ghidra script.
However, conversion to Ghidra can end up with a slightly different output from the original due to the complexity of the original IDA script.
So, I highly recommend creating the new training, test dataset, and BPE tokenizer with your Ghidra script before training/inference with AsmDepictor.

Thank you,

HyunJin Kim.
